=== gaiaBuildSystem/gaia/schema/recipe.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Gaia Package",
    "type": "object",
    "properties": {
        "name": {
            "description": "The name of the Recipe",
            "type": "string"
        },
        "type": {
            "description": "The type of the Recipe",
            "type": "string",
            "enum": [
                "bootloader",
                "package",
                "rootfs",
                "init",
                "config",
                "kernel",
                "kernelModule",
                "application"
            ]
        },
        "priority": {
            "description": "The priority of the Recipe. This will use if there are multiple recipes discovery with the same name. So, the property from the recipe with the highest priority will be used.",
            "type": "number"
        },
        "buildDependencies": {
            "description": "The dependencies of the Recipe. This property is used to define other recipes that must be built before this one.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "source": {
            "description": "The source of the Recipe. Was designed to be a git repository or an URL to a tarball or file to be fetched.",
            "type": "string",
            "pattern": "^$|^(http|https)://[^ \"]+$"
        },
        "file": {
            "description": "The file to be fetched from the source. If the source is a git repository, this property will be ignored.",
            "type": "string"
        },
        "files": {
            "description": "The files to be fetched from the source. If the source is a git repository, this property will be ignored.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "support": {
            "description": "This property is used to define the supported architectures of the recipe.",
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "linux/amd64",
                    "linux/arm64"
                ]
            },
            "minItems": 1
        },
        "ref": {
            "description": "The git reference to be fetched. If the source is a git repository, this property will be used to define the reference to be fetched.",
            "type": "object",
            "properties": {
                "linux/amd64": {
                    "type": "string"
                },
                "linux/arm64": {
                    "type": "string"
                }
            }
        },
        "checksum": {
            "description": "The checksum of the file to be fetched. If the source is a git repository, this property will be ignored.",
            "type": "object",
            "properties": {
                "linux/amd64": {
                    "type": "string"
                },
                "linux/arm64": {
                    "type": "string"
                }
            }
        },
        "hostAsContainer": {
            "description": "This property is used to define if the recipe should be built inside a container.",
            "type": "boolean",
            "default": false
        },
        "containerImage": {
            "description": "This property is used to define the container to be used to build the recipe.",
            "type": "object",
            "properties": {
                "image": {
                    "description": "The image of the Recipe. This property is used to define the image to be used to build the recipe.",
                    "type": "string"
                },
                "tag": {
                    "description": "The tag of the Recipe. This property is used to define the tag of the image to be used to build the recipe.",
                    "type": "string"
                },
                "extraConfig": {
                    "description": "The extra configuration for the container. The Gaia will bind and do some automatically configuration to run the container based in the image:tag, but some images need extra configurations like `--entrypoint=\"\"`.",
                    "type": "string"
                }
            },
            "required": [
                "image",
                "tag"
            ]
        },
        "hostDeps": {
            "description": "The host dependencies of the Recipe. This property is used by the main script check if the environment has the necessary dependencies to build the recipe.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "beforeTargetDepsRecipes": {
            "description": "This property is used to define the beforeTargetDeps scripts. They should be executable capable files and will be executed in the fetch stage.",
            "type": "array",
            "items": {}
        },
        "targetDeps": {
            "description": "The target dependencies of the Recipe. This property is used by the main script to install into the image the necessary dependencies to build the recipe. It can be an array, used for any Debian release, or an object with an array per Debian release, where only the one matching the distro debian property is used.",
            "oneOf": [
                {
                    "type": "array",
                    "items": {}
                },
                {
                    "type": "object",
                    "properties": {
                        "bookworm": {
                            "type": "array",
                            "items": {}
                        },
                        "trixie": {
                            "type": "array",
                            "items": {}
                        },
                        "forky": {
                            "type": "array",
                            "items": {}
                        }
                    },
                    "additionalProperties": false
                }
            ]
        },
        "afterTargetDepsRecipes": {
            "description": "This property is used to define the afterTargetDepsRecipes scripts. They should be executable capable files and will be executed in the fetch stage.",
            "type": "array",
            "items": {}
        },
        "env": {
            "description": "The environment variables of the Recipe. This property is used by the main script to set the environment variables to build the recipe.",
            "type": "object"
        },
        "customData": {
            "description": "A custom object that will be shared to the build context.",
            "type": "object"
        },
        "fetchRecipes": {
            "description": "This property is used to define the fetch scripts. They should be executable capable files and will be executed in the fetch stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "patchRecipes": {
            "description": "This property is used to define the patch scripts. They should be executable capable files and will be executed in the patch stage.",
            "type": "array",
            "items": {}
        },
        "buildRecipes": {
            "description": "This property is used to define the build scripts. They should be executable capable files and will be executed in the build stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "beforeDeployRecipes": {
            "description": "This property is used to define the before deploy scripts. They should be executable capable files and will be executed in the before deploy stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "deployPureRecipes": {
            "description": "This property is used to define the pure deploy scripts. Pure deploy means that these does not depends on having rootfs. They should be executable capable files and will be executed in the pure deploy stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "deployRecipes": {
            "description": "This property is used to define the deploy scripts. They should be executable capable files and will be executed in the deploy stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "afterDeployRecipes": {
            "description": "This property is used to define the after deploy scripts. They should be executable capable files and will be executed in the after deploy stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "bundleRecipes": {
            "description": "This property is used to define the bundle scripts. They should be executable capable files and will be executed in the bundle stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "afterBundleRecipes": {
            "description": "This property is used to define the after bundle scripts. They should be executable capable files and will be executed in the after bundle stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "cleanRecipes": {
            "description": "This property is used to define the clean scripts. They should be executable capable files and will be executed in the clean stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "initramfsRecipes": {
            "description": "This property is used to define the initramfs scripts. They should be executable capable files and will be executed in the initramfs stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "afterDeployInitramfsRecipes": {
            "description": "This property is used to define the after deploy initramfs scripts. They should be executable capable files and will be executed in the after deploy initramfs stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "afterBundleInitramfsRecipes": {
            "description": "This property is used to define the after bundle initramfs scripts. They should be executable capable files and will be executed in the after bundle initramfs stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "sbomRecipes": {
            "description": "This property is used to define the SBOM scripts. They should be executable capable files and will be executed in the SBOM stage.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "merge": {
            "description": "This property is used to define if the recipes should be merged with the existing ones.",
            "type": "boolean"
        },
        "version": {
            "description": "The version of the Recipe. This property is used to define the version of the recipe.",
            "type": "string"
        }
    },
    "allOf": [
        {
            "if": {
                "properties": {
                    "hostAsContainer": {
                        "const": true
                    }
                },
                "required": [
                    "hostAsContainer"
                ]
            },
            "then": {
                "required": [
                    "containerImage"
                ]
            },
            "else": {}
        }
    ],
    "required": [
        "name",
        "type",
        "priority",
        "support"
    ]
}

=== gaiaBuildSystem/gaia/cookbook/recipes-init/initramfs-php/initramfs.json
{
    "name": "initramfs",
    "type": "init",
    "priority": 0,
    "support": [
        "linux/amd64",
        "linux/arm64"
    ],
    "targetDeps": [
        "curl",
        "cpio",
        "gzip",
        "binutils",
        "patchelf",
        "python3",
        "python3-pip",
        "scons",
        "php",
        "busybox-static",
        "fbset",
        "fbi"
    ],
    "afterDeployRecipes": [
        "build.ts"
    ]
}

=== gaiaBuildSystem/gaia/cookbook/recipes-common/os-release/os-release.json
{
    "name": "os-release",
    "type": "config",
    "priority": 0,
    "support": [
        "linux/amd64",
        "linux/arm64"
    ],
    "env": {
        "OS_RELEASE_PRETTY_NAME": "DeimOS Reference Distro",
        "OS_RELEASE_NAME": "DeimOS",
        "OS_RELEASE_ID": "deimOS",
        "OS_RELEASE_VERSION_CODENAME": "gaia",
        "OS_RELEASE_HOME_URL": "https://github.com/gaiaBuildSystem",
        "OS_RELEASE_BUG_REPORT_URL": "https://github.com/gaiaBuildSystem",
        "OS_RELEASE_SUPPORT_URL": "https://github.com/gaiaBuildSystem",
        "OS_RELEASE_VARIANT": "reference"
    },
    "deployRecipes": [
        "deploy.ts"
    ]
}

=== gaiaBuildSystem/gaia/cookbook/recipes-bsp/grub/grub.json
{
    "name": "grub2",
    "type": "bootloader",
    "priority": 0,
    "support": [
        "linux/amd64"
    ],
    "ref": {},
    "hostDeps": [
        "grub2-common",
        "grub-pc-bin"
    ],
    "targetDeps": [],
    "fetchRecipes": [],
    "patchRecipes": [],
    "buildRecipes": [],
    "deployRecipes": [
        "deploy.ts"
    ],
    "cleanRecipes": []
}

=== gaiaBuildSystem/gaia/cookbook/recipes-debian/bookworm/bookworm.json
{
    "name": "debian-bookworm",
    "type": "rootfs",
    "priority": 0,
    "support": [
        "linux/amd64",
        "linux/arm64"
    ],
    "checksum": {
        "linux/amd64": "3f03ff2fca74e47cee05599e36e1f1258d386895a3394b3683df333f404f4e8a",
        "linux/arm64": "53692cdc49e2b0abdd9adf36466b366aaebdbbdbb2e6a7f432e2b4fb7327fd93"
    },
    "env": {
        "BOOT_LABEL": "BOOT",
        "ROOT_LABEL": "gaia"
    },
    "hostDeps": [
        "mount",
        "xz-utils",
        "kpartx",
        "e2fsprogs",
        "pipx",
        "lz4",
        "xterm"
    ],
    "targetDeps": [
        "kmod",
        "locales",
        "sudo",
        "bash",
        "bash-completion",
        "util-linux",
        "htop",
        "e2fsprogs",
        "parted",
        "dbus",
        "udev",
        "network-manager",
        "polkitd",
        "net-tools",
        "resolvconf"
    ],
    "fetchRecipes": [
        "fetch.ts"
    ],
    "patchRecipes": [],
    "buildRecipes": [
        "disk.ts",
        "buildRootfs.ts"
    ],
    "deployRecipes": [
        "update.ts"
    ],
    "sbomRecipes": [
        "sbom.ts"
    ],
    "cleanRecipes": [
        "umount.ts"
    ]
}

=== gaiaBuildSystem/gaia/cookbook/recipes-common/fastfetch/fastfetch.json
{
    "name": "fastfetch",
    "type": "application",
    "priority": 0,
    "support": [
        "linux/amd64",
        "linux/arm64"
    ],
    "source": "https://github.com/gaiaBuildSystem/fastfetch.git",
    "version": "2.38.0",
    "ref": {
        "linux/amd64": "83878c59a7e2613dbf6cfc8419106d96d6796bf4",
        "linux/arm64": "83878c59a7e2613dbf6cfc8419106d96d6796bf4"
    },
    "env": {
        "ALIAS_NEOFETCH": "true"
    },
    "hostAsContainer": true,
    "containerImage": {
        "image": "debian",
        "tag": "bookworm"
    },
    "hostDeps": [
        "binutils",
        "build-essential",
        "cmake",
        "libdrm-dev",
        "libglib2.0-dev",
        "libdconf-dev",
        "libchafa-dev",
        "zlib1g-dev",
        "libdbus-1-dev",
        "libosmesa6-dev",
        "libopencl-clang-15-dev",
        "directx-headers-dev"
    ],
    "targetDeps": {
        "bookworm": [
            "libdrm2",
            "libosmesa6"
        ],
        "forky": [
            "libdrm2"
        ]
    },
    "fetchRecipes": [
        "fetch.ts"
    ],
    "buildRecipes": [
        "build.sh"
    ],
    "deployRecipes": [
        "deploy.ts"
    ],
    "sbomRecipes": [
        "fastfetch-sbom.ts"
    ]
}

=== gaiaBuildSystem/gaia/cookbook/recipes-init/initramfs/initramfs.json
{
    "name": "initramfs",
    "type": "init",
    "priority": 0,
    "support": [
        "linux/amd64"
    ],
    "targetDeps": [
        "curl",
        "cpio",
        "gzip",
        "binutils",
        "patchelf",
        "python3",
        "python3-pip",
        "php",
        "busybox-static",
        "fbset",
        "fbi"
    ],
    "afterDeployRecipes": [
        "build.ts"
    ]
}

=== gaiaBuildSystem/gaia/cookbook/recipes-common/userlogin/userlogin.json
{
    "name": "userlogin",
    "type": "config",
    "priority": 0,
    "support": [
        "linux/amd64",
        "linux/arm64"
    ],
    "env": {
        "USER_LOGIN_USER": "reference",
        "USER_LOGIN_PASSWORD": "reference",
        "USER_ROOT_PASSWORDLESS": "true",
        "USER_DEFAULT_SHELL": "/bin/bash"
    },
    "hostDeps": [
        "whois",
        "sudo"
    ],
    "afterDeployRecipes": [
        "create.ts"
    ]
}

=== gaiaBuildSystem/gaia/cookbook/recipes-bsp/u-boot-ram/u-boot-ram.json
{
    "name": "u-boot-ram",
    "type": "bootloader",
    "priority": 0,
    "source": "https://github.com/gaiaBuildSystem/u-boot",
    "support": [
        "linux/arm64"
    ],
    "ref": {
        "linux/arm64": "25049ad560826f7dc1c4740883b0016014a59789"
    },
    "hostDeps": [
        "git"
    ],
    "targetDeps": [
        "u-boot-tools"
    ],
    "fetchRecipes": [
        "fetch.ts"
    ],
    "patchRecipes": [],
    "buildRecipes": [
        "build.ts"
    ]
}
